// Flat config. `.nuxt/eslint.config.mjs` is generated by @nuxt/eslint and
// already includes the Vue + TypeScript + Nuxt rulesets.
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  // Must stay a lone `ignores` key: in flat config an object with any other
  // key becomes a per-config filter instead of a global ignore list.
  {
    ignores: ['.nuxt/**', '.output/**', 'dist/**', 'coverage/**', 'docs/**']
  },
  {
    rules: {
      'vue/multi-word-component-names': 'off'
    }
  }
)
